# Generated by Django 2.2.12 on 2020-05-13 07:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioId', models.CharField(max_length=35)),
                ('FotoUser', models.ImageField(default='user.png', upload_to='', verbose_name='Foto de perfil')),
                ('TeleUser', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HabilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombHabil', models.CharField(max_length=155)),
                ('DescHabil', ckeditor.fields.RichTextField(default='Desarrollador...', max_length=2000, verbose_name='Descripcion de la habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrcHabil', models.DecimalField(decimal_places=1, max_digits=2)),
                ('udtHabil', models.DateTimeField(auto_now=True)),
                ('idHabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.HabilUser')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
        ),
        migrations.CreateModel(
            name='DetaRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agregado', models.DateTimeField(auto_now_add=True)),
                ('udtAgregado', models.DateTimeField(auto_now=True)),
                ('EstaRol', models.CharField(max_length=45)),
                ('idRoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
        ),
    ]
