# Generated by Django 2.2.12 on 2020-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200513_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosuser',
            name='UpdAddData',
            field=models.DateTimeField(auto_now=True, null='True', verbose_name='Modificado el'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='datosuser',
            name='addData',
            field=models.DateTimeField(auto_now_add=True, null='True', verbose_name='Creado el'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='datosuser',
            name='apeUser',
            field=models.CharField(max_length=256, null='True', verbose_name='Apellidos'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='datosuser',
            name='geneUser',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='datosuser',
            name='nomUser',
            field=models.CharField(max_length=256, null='True', verbose_name='Nombres'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='datosuser',
            name='profeUser',
            field=models.CharField(max_length=100, null='True', verbose_name='Profesion'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='TeleUser',
            field=models.CharField(max_length=45, verbose_name='Numero de Teléfono'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='usuarioId',
            field=models.CharField(max_length=35, verbose_name='Identificacion'),
        ),
    ]
