# Generated by Django 2.2.12 on 2020-05-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200513_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaroles',
            name='Agregado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Agregado el'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='EstaRol',
            field=models.CharField(max_length=45, verbose_name='Estado del Rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='idRoles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Id del Rol'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='idUsuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del Usuario'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='udtAgregado',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='habiluser',
            name='nombHabil',
            field=models.CharField(max_length=155, verbose_name='Nombre de la Habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='PrcHabil',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Porcentaje de la Habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='idHabil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.HabilUser', verbose_name='Id de la Habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='idUsuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del Usuario'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='udtHabil',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizacion del Porcentaje'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='RoleName',
            field=models.CharField(max_length=50, verbose_name='Nombre del Rol'),
        ),
    ]
