# Generated by Django 2.2.12 on 2020-05-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0004_auto_20200513_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lenguaje', models.CharField(max_length=45, verbose_name='Lenguaje de Programacion')),
                ('MotorDB', models.CharField(max_length=155, verbose_name='Motor Base de Datos')),
                ('Arquitecura', models.CharField(max_length=255, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Categoria del Proyecto',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTiDoc', models.CharField(max_length=45, verbose_name='Nombre Tipo Documentacion')),
            ],
            options={
                'verbose_name': 'Tipo de Documuentos',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombProy', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('DescProy', models.TextField(default='Programa de desarrollo de Software', verbose_name='Descripcion del proyecto')),
                ('ImgProye', models.ImageField(default='proyecto.png', upload_to='', verbose_name='Foto del proyecto')),
                ('FechaIni', models.DateTimeField(auto_now_add=True, null='True', verbose_name='Inicio el')),
                ('FechaFin', models.DateTimeField(auto_now_add=True, null='True', verbose_name='Finalizo el')),
                ('UrlRepo', models.TextField(default='No tiene repositorio en GitHub', verbose_name='Url del Repositorio en GitHub')),
                ('EstaProy', models.CharField(max_length=45, verbose_name='Estado del Proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Id de la Categoria')),
            ],
            options={
                'verbose_name': 'Datos del proyecto',
                'verbose_name_plural': 'Informacion de los Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDocu', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('PathDocu', models.CharField(max_length=45, verbose_name='Ruta de almacenamiento del Documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Id del Proyecto')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Id Tipo Documento')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del Usuario')),
            ],
            options={
                'verbose_name': 'Datos del Documento',
                'verbose_name_plural': 'Informacion de los Documentos',
            },
        ),
    ]
